FROM alpine:latest

RUN apk add --no-cache curl
RUN curl -fsSL https://raw.githubusercontent.com/you54f/pact-ruby-standalone/master/install.sh | sh \
     && ln -s /pact/bin/* /usr/local/bin

ENTRYPOINT ["pact-mock-service"]