FROM arm64v8/alpine

# COPY install.sh /install.sh
# RUN chmod +x /install.sh && /install.sh && ln -s /pact/bin/* /usr/local/bin

RUN curl -fsSL https://raw.githubusercontent.com/you54f/pact-ruby-standalone/master/install.sh | sh \
     && ln -s /pact/bin/* /usr/local/bin

ENTRYPOINT ["pact-mock-service"]