#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["BUNDLE_GEMFILE"] ||= File.expand_path("./Gemfile", __dir__)
require "bundler/setup"
ARGV.push("start", "-R", "#{File.dirname(__FILE__)}/config.ru", "-p 9292") if ARGV.empty?
if ARGV.include?("--with-ssl")
  ARGV.delete("--with-ssl")
  ARGV.push("start", "-R", "#{File.dirname(__FILE__)}/config.ru", "-p 9292")
  crt_file = File.join(Dir.pwd, "server.crt")
  key_file = File.join(Dir.pwd, "server.key")

  unless File.exist?(crt_file) && File.exist?(key_file)
    system("openssl req -x509 -newkey rsa:4096 -nodes -keyout #{key_file} -out #{crt_file} -days 365 -subj '/CN=localhost'")
  end

  ARGV.push("--ssl", "--ssl-cert-file", crt_file, "--ssl-key-file", key_file)
end
load Gem.bin_path("thin", "thin")
