source 'https://rubygems.org'

gem "pact", "1.67.2"
gem "pact-message", "0.11.1"
gem "pact-mock_service", "3.12.3"
gem "pact-provider-verifier", "1.39.1"
gem "webrick", "1.9.1"
# pinned to versions available from traveling-ruby
# gem "json", "2.16.0"
# gem "bigdecimal", "3.3.1"

gem "json", "2.9.1"
# gem "bigdecimal", "3.1.8"
